version: '3'

services:
  mony-db:
    image: postgres:latest
    container_name: mony-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mony
      - POSTGRES_PASSWORD=ofKGtWwgYcsLuGyKmsVJ
      - POSTGRES_DB=mony-db
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    depends_on:
      - mony-db
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=victorcolina@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json
